### ISSUE TITLE
Problem with enchantments on armor

### ISSUE THREAD

**Issue by Gohansuperd** [meowsome/EnchantmentUpgrades#1]
Hi, I was configuring this plugin and I need to upgrade enchantments with armors, but for some reason, when I shift + right click with an armor on my hand, it doesn't works. I really need it soon. Other tools works perfectly.

Version: 1.19
Plugin version: 0.1.1
Software: Purpur

**Comment by meowsome** [comment]
Hey, this plugin hasn't been tested on 1.19 yet. I see you closed the issue. Did you figure it out?
